### ISSUE TITLE
Is it possible to make a logger output colorful like in `mix test`?

### ISSUE THREAD

**Issue by astery** [lpil/mix-test.watch#49]
``` elixir
defmodule Test do
  use ExUnit.Case
  require Logger

  test "color" do
    Logger.warn "warn"
    Logger.error "error"
  end
end
```

![selection_004](https://cloud.githubusercontent.com/assets/1290275/19043174/1996a0fc-89a0-11e6-897f-64951c7c2490.png)
![selection_005](https://cloud.githubusercontent.com/assets/1290275/19043175/1ccc4bbe-89a0-11e6-9ccf-71cb923730fe.png)

**Comment by lpil** [comment]
Huh, interesting. I thought it would have been coloured. Thanks for the report.

**Comment by doughsay** [comment]
You can also see this happening if you run the `dialyzer` task from here: https://github.com/jeremyjh/dialyxir.

Running the task on its own produces colored output, whereas using test.watch removes the colors.

Interestingly, as shown in the screenshots above, not ALL colors are removed, just some...

**Comment by shawarmaz** [comment]
@lpil gentle bump, any news on this?

**Comment by lpil** [comment]
Hi @shawarmaz , I am busy working on https://github.com/gleam-lang/gleam/ I'm afraid!

**Comment by danielspofford** [comment]
This fixed all color issues for me:

```elixir
config :mix_test_watch,
  cli_executable: "elixir --erl \"-elixir ansi_enabled true\" -S mix"
```

The root of the issue was whether ANSI escapes are enabled or not. Elixir configures this automatically based on whether stdout and stderr are attached to ttys or not (unless it has already been configured, but more on that later). This helps https://github.com/lpil/mix-test.watch/blob/f5235c247520b132d50994efd9bca40ce62d312e/lib/mix_test_watch/port_runner/port_runner.ex#L44 for things that query the config after it has ran, for example, test dots being green or not. But it does not help for things that already queried it before it ran and don't check again. Notably, Logger starts before it gets updated which causes its formatter's color's [enabled key](https://github.com/elixir-lang/elixir/blob/main/lib/logger/lib/logger/formatter.ex#L175) to be false, resulting in dreary Logger logs.

The fix works by using `elixir` instead of `mix` as the initial command so we can use `--erl` to pass a [user flag](https://www.erlang.org/doc/man/erl#flags) to Erlang. In particular, it is passing `-Application Par Val` as `-elixir ansi_enabled true`. This causes that value to be set in the application env before any applications are started (preventing Elixir from automatically configuring it to false in this case). So when Logger eventually does start, the value is true already, instead of it still being false because the port runner update hasn't had a chance to run yet.
