### ISSUE TITLE
Remove bash dependency

### ISSUE THREAD

**Issue by bentruyman** [lpil/mix-test.watch#8]
`bash` is used [here](https://github.com/lpil/mix-test.watch/blob/adf08bddc445383656262f4497b7b8517106a921/lib/mix_test_watch.ex#L47) but isn't available on all platforms. To be more specific, I'm running Elixir in a Docker container based on Alpine Linux which only ships with a version of `sh`. `sh` seems pretty common across most *nix environments, and I imagine the line I referenced above could be modified to use `sh` making this project compatible with a wider range of use cases.

**Comment by lpil** [comment]
Sounds like a good idea. :)

**Comment by bentruyman** [comment]
Seems to work the same in `sh`:
```sh
sh -c 'FOO=foo env | grep FOO'
```

**Comment by lpil** [comment]
Well that should be nice and simple then. Wanna make a pull request? :)

**Comment by bentruyman** [comment]
[Done](https://github.com/lpil/mix-test.watch/pull/9). :smile:

**Comment by lpil** [comment]
I have a question- how does this work in a docker container? I tried it with vagrant with the project directory mounted from the host, but it didn't work because when I edit files on the host it doesn't emit file system events on the guest.

I understand that docker doesn't use virtualisation on Linux. Are you on Linux?

**Comment by lpil** [comment]
Also, what makes you like Docker for Elixir? Trying to decide if I should dedicate time to learning it. :)
